Ocean Waves improvements
Exawind/amr-wind pull request #1152
Opened 2024-07-24 16:00 UTC by mbkuhn

## Summary

Collection of improvements for the Ocean Waves functionality.

## Pull request type

- [x] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [x] Documentation content changes
- [ ] Other (please describe):

## Checklist

The following is included:

- [ ] new unit-test(s)
- [ ] new regression test(s)
- [ ] documentation for new capability

This PR was tested by running:

- the unit tests
  - [ ] on GPU 
  - [ ] on CPU 
- the regression tests
  - [ ] on GPU 
  - [ ] on CPU

2024-07-24 21:00 UTC, mbkuhn commented
diffs (as expected) introduced in ow_linear, ow_stokes, and abl_multiphase_laminar. relatively minor diffs, except for ow_stokes because the domain has changed.

2024-07-25 17:31 UTC, marchdf requested changes

2024-07-25 17:31 UTC, marchdf commented on amr-wind/ocean_waves/relaxation_zones/relaxation_zones_ops.cpp
> +        pp.query("numerical_beach_lfactor", wdata.beach_length_factor);
more descriptive user facing option? `numerical_beach_length_factor` ?

2024-07-25 17:31 UTC, marchdf commented on amr-wind/ocean_waves/relaxation_zones/stokes_waves_ops.H
> +            const amrex::Real waveheight = wdata.wave_height;
for these 3, maybe for consistency with the rest: `wave_*` / `water_*`?

2024-07-25 21:28 UTC, marchdf commented
Test pass for me on CPU (other than the ones you noted).

2024-07-25 21:28 UTC, marchdf approved these changes

2024-07-25 21:47 UTC, merged