Improve initialization of zalesak case
Exawind/amr-wind pull request #1223
Opened 2024-08-30 20:31 UTC by mbkuhn

## Summary

Improve the setup of the levelset field for the zalesak case. Spurious artifacts can be created at different resolutions with the current approach.

## Pull request type

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## Checklist

The following is included:

- [ ] new unit-test(s)
- [ ] new regression test(s)
- [ ] documentation for new capability

This PR was tested by running:

- the unit tests
  - [ ] on GPU 
  - [ ] on CPU 
- the regression tests
  - [ ] on GPU 
  - [ ] on CPU 

## Additional background

This didn't actually do much to change the convergence behavior, but since I went through the effort of trying it, we might as well add the improvement.

2024-08-30 20:52 UTC, mbkuhn commented
Artifact above the slot is now gone (before, after)
<img width="1191" alt="Screenshot 2024-08-30 at 2 46 56 PM" src="https://github.com/user-attachments/assets/1e9a58c5-4055-4dac-a6f1-02d2cc4297a7">

<img width="1191" alt="Screenshot 2024-08-30 at 2 46 10 PM" src="https://github.com/user-attachments/assets/bf662b4a-15cb-49b5-8d3c-e7777bda15bc">

2024-08-30 20:53 UTC, mbkuhn commented
bottom of slot is more consistent across resolutions now, compare to above (before, after)

<img width="1191" alt="Screenshot 2024-08-30 at 2 47 11 PM" src="https://github.com/user-attachments/assets/a79ccd98-7928-43db-aa49-717a6fbf826b">

<img width="1191" alt="Screenshot 2024-08-30 at 2 50 26 PM" src="https://github.com/user-attachments/assets/e53cde29-8421-4bfb-ab37-63ea34ae5333">

2024-08-30 20:54 UTC, mbkuhn commented
The levelset field is way smoother and consistent now, too (before, after)
<img width="1191" alt="Screenshot 2024-08-30 at 2 51 25 PM" src="https://github.com/user-attachments/assets/9d62649f-f83b-4c78-9576-f863bfebd567">

<img width="1191" alt="Screenshot 2024-08-30 at 2 51 17 PM" src="https://github.com/user-attachments/assets/5a8f7145-3a4b-46a0-8336-27c4de77f80f">

2024-08-30 20:55 UTC, mbkuhn commented
I also did checks in 3D and on the yz plane, but I figured this was enough pictures.

2024-09-03 15:25 UTC, marchdf requested changes

2024-09-03 15:25 UTC, marchdf commented on amr-wind/physics/multiphase/ZalesakDiskScalarVel.H
> +    amrex::Real m_hwidth{0.04};
Name it the same as in the other class? `m_halfwidth` ?

2024-09-03 15:25 UTC, marchdf commented on amr-wind/physics/multiphase/ZalesakDiskScalarVel.cpp
> +                bool in_slot_x_ymin =
`const` these two bools

2024-09-03 16:00 UTC, marchdf approved these changes

2024-09-03 16:30 UTC, merged