Specified Monin-Obukhov Length
Exawind/amr-wind pull request #1418
Opened 2024-12-20 16:08 UTC by hgopalan

There are three ways to specify non-neutral stratification for ABL simulations: (i) specified heat-flux, (ii) specified temperature or heating/cooling rate and (iii) specified Monin-Obukhov length. This PR adds the capability for the third methodology in which the Monin-Obukhov length is kept constant. This method is used often in RANS simulations to do wind turbine siting for non-neutral cases (faster convergence rate) and minimize the mismatch between wall boundary condition and inflow profile. 

Please check the type of change introduced:

- [ ] Bugfix
- [X ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## Checklist

The following is included:

- [ ] new unit-test(s)
- [ ] new regression test(s)
- [ ] documentation for new capability

This PR was tested by running:

- the unit tests
  - [ ] on GPU 
  - [X ] on CPU 
- the regression tests
  - [ ] on GPU 
  - [ ] on CPU 

To be added: 
1. New unit test 
2. New regression test 
3.  Documentation

2025-02-24 06:07 UTC, hgopalan commented
Need additional test cases for immersed forcing

2025-02-24 18:57 UTC, moprak-nrel requested changes

2025-02-24 18:57 UTC, moprak-nrel commented on amr-wind/equation_systems/temperature/source_terms/DragTempForcing.H
> +    static amrex::Real stability(
This function seems to be getting repeated implementations across multiple files? Just have one and call those?

2025-02-24 18:57 UTC, moprak-nrel commented on test/test_files/abl_specifiedmol_neutral/rans_1d.info
Is the rans_1d.info file identical across the cases? You might be able to just have one and reuse it for the other tests?

2025-02-24 18:57 UTC, moprak-nrel commented on amr-wind/equation_systems/icns/source_terms/DragForcing.cpp
> +    amrex::Real non_neutral_neighbour = 0.0;
Can you const these with a ternary expression?

2025-02-24 18:57 UTC, moprak-nrel commented on amr-wind/equation_systems/icns/source_terms/DragForcing.cpp
> +                ustar / kappa * (std::log(0.5 * dx[2] / z0) - non_neutral_cell);
Are these calcs/the model going to be in the documentation? Not sure how to interpret `non_neutral_cell` and `non_neutral_neighbor`.

2025-02-24 18:57 UTC, moprak-nrel commented on amr-wind/equation_systems/temperature/source_terms/DragTempForcing.cpp
> +    const amrex::Real gravity_mod = 9.81;
Do you want to be using the value of gravity from the input file? We have `incflo.gravity` or some such right?

2025-02-24 18:57 UTC, moprak-nrel commented on amr-wind/equation_systems/tke/source_terms/KransAxell.H
> +    static amrex::Real stability(
Same comment as repeated definition of this function

2025-02-24 18:57 UTC, moprak-nrel commented on amr-wind/wind_energy/ABLWallFunction.cpp
> +                        amrex::Real x =
This variable name is confusing, this is not `plo + i*dx`.

2025-02-24 18:57 UTC, moprak-nrel commented on amr-wind/wind_energy/ABLWallFunction.cpp
> +                            const amrex::Real theta2 = told_arr(i, j, k);
maybe a more descriptive variable name? you have `theta2` to refer to `theta` at k+1 in a different place.

2025-02-24 19:23 UTC, hgopalan commented on amr-wind/equation_systems/temperature/source_terms/DragTempForcing.H
> +    static amrex::Real stability(
I did not know how to do that across namespaces so created one at every place.

2025-02-24 19:23 UTC, hgopalan commented on test/test_files/abl_specifiedmol_neutral/rans_1d.info
No they are different for each case.

2025-02-24 19:24 UTC, hgopalan commented on amr-wind/equation_systems/icns/source_terms/DragForcing.cpp
> +                ustar / kappa * (std::log(0.5 * dx[2] / z0) - non_neutral_cell);
The walk through talks about the details already. The non_neutral are stability function corrections.

2025-02-24 19:28 UTC, hgopalan commented on amr-wind/equation_systems/temperature/source_terms/DragTempForcing.cpp
> +        const amrex::Real surf_temp =
For terrain, the value at the point above the cell is computed from the solution as it is not a wall. However, we need to force a MOST boundary condition as a forcing term. So we correct the theta at the cell using the cell above it by computing what is the MOST solution. We already had this in place for wind speed. It gets more complicated with temperature.

2025-02-24 19:29 UTC, hgopalan commented on amr-wind/wind_energy/ABLWallFunction.cpp
> +                            const amrex::Real theta2 = told_arr(i, j, k);
In this case the value at k is correct so I am referring to it as theta2.

2025-02-24 19:36 UTC, hgopalan commented on amr-wind/wind_energy/ABLWallFunction.cpp
> +                        amrex::Real x =
Copied from here: https://github.com/Exawind/amr-wind/blob/main/amr-wind/wind_energy/MOData.cpp

2025-02-24 19:39 UTC, moprak-nrel commented on amr-wind/equation_systems/temperature/source_terms/DragTempForcing.H
> +    static amrex::Real stability(
You could just put it in a common place and call it across the places you need. For instance you could add these in some type of wall function utilities. We don't want to be repeating code.

2025-02-24 19:41 UTC, moprak-nrel commented on amr-wind/wind_energy/ABLWallFunction.cpp
> +                        amrex::Real x =
Why not just call that function?

2025-02-24 19:47 UTC, moprak-nrel commented on amr-wind/wind_energy/ABLWallFunction.cpp
> +                        amrex::Real x =
Also context matters, that is a standalone small function where `x` isn't going to get confused with the spatial direction. Which isn't the case in your code.

2025-02-24 20:19 UTC, hgopalan commented on amr-wind/wind_energy/ABLWallFunction.cpp
> +                        amrex::Real x =
> Why not just call that function?

I want to have the flexibility of using a different stability function in the future within the context of this model. Currently it is set to the same as the one in MODData.H.

2025-02-24 20:28 UTC, moprak-nrel commented on amr-wind/wind_energy/ABLWallFunction.cpp
> +                        amrex::Real x =
In that case, create a function for calculating `psi_m/psi_h` in your namespace and call the `MOData` function within that. Or simply just call the MOData function for now, and replace it when you add a different stability function.

2025-03-19 17:43 UTC, marchdf requested changes

2025-03-19 17:43 UTC, marchdf commented on docs/sphinx/user/inputs_ABL.rst
> +.. input_param:: ABL.wall_het_model
what is `het` ? Can we make it a more explicit user param?

2025-03-19 17:43 UTC, marchdf commented on docs/sphinx/user/inputs_ABL.rst
> +.. input_param:: ABL.mol_length
what is `mol`? Worried this user facing param is going to conflict with the MOL advection numerics option.

2025-03-19 17:43 UTC, marchdf commented on amr-wind/wind_energy/ABLWallFunction.H
> +    amrex::Real m_mol_length{-1e30};
instead of `-1e30` can you use a value from the `constants` namespace?

2025-03-19 17:46 UTC, hgopalan commented on docs/sphinx/user/inputs_ABL.rst
> +.. input_param:: ABL.mol_length
mol for Monin-Obuknov length. We can change it to a different name if necessary

2025-03-19 17:47 UTC, hgopalan commented on docs/sphinx/user/inputs_ABL.rst
> +.. input_param:: ABL.wall_het_model
het to represent heterogenous model. I can expand it out.

2025-03-19 18:22 UTC, marchdf commented on docs/sphinx/user/inputs_ABL.rst
> +.. input_param:: ABL.mol_length
that would be great!

2025-04-08 18:13 UTC, moprak-nrel commented
@hgopalan I've done a bunch of the C++ lift, and addressed comments from me and @marchdf. Can you take a look to make sure I haven't made any behavior changes?

Also can you address the merge conflicts? Seems like there's a conflict in `DragForcing` that needs to be addressed. 

We also need @marchdf  or someone else to review since I've become a significant contributor to this PR ;) 

Final minor point, the regtest `abl_specifiedmol_neutral` does not have a `monin_obuknov_length` specified in the input, is this intended? That's the only diff I see before and after my changes in the new regtests.

2025-04-08 18:16 UTC, hgopalan commented
> @hgopalan I've done a bunch of the C++ lift, and addressed comments from me and @marchdf. Can you take a look to make sure I haven't made any behavior changes?
> 
> Also can you address the merge conflicts? Seems like there's a conflict in `DragForcing` that needs to be addressed.
> 
> We also need @marchdf or someone else to review since I've become a significant contributor to this PR ;)
> 
> Final minor point, the regtest `abl_specifiedmol_neutral` does not have a `monin_obuknov_length` specified in the input, is this intended? That's the only diff I see before and after my changes in the new regtests.

For neutral cases we do not need it.

2025-04-22 16:04 UTC, mbkuhn commented on amr-wind/equation_systems/icns/source_terms/DragForcing.H
> +
```suggestion
```

2025-04-22 16:04 UTC, mbkuhn commented on amr-wind/equation_systems/icns/source_terms/DragForcing.H
> +
```suggestion
```

2025-04-22 16:56 UTC, merged