Meso-Micro Coupling with no precursor for Terrain
Exawind/amr-wind pull request #1426
Opened 2024-12-27 16:25 UTC by hgopalan

The current workflow in AMR - Wind requires a precursor simulation to generate boundary plane for running complex terrain simulations. However, this is not a requirement. This PR proposes an alternative path for running simulations over complex terrain. 

1. Based on met-mast measurement, a 1-D vertical wind profile is created along with the required geostrophic wind. 
2. The simulation is initialized with the 1-D profile. 
3.  All the horizontal boundary conditions are replaced with pressure-outflow boundary condition with a sponge layer, forcing the 1-D profile. 
4.  A forcing zone is added on the upper portion of the domain to drive the wind speed and temperature to be consistent with the 1-D vertical profile. 

Future Work:

1. Adding the nudging terms within domain for met-mast or Lidar data 
2.  Replacing pressure-outflow with WRF-mesoscale boundary plane data and removing the flat terrain restrictions at the boundary. 

Please check the type of change introduced:

- [ ] Bugfix
- [ X] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

To Do: 
1. Regression test 
2. Unit test 
3.  Documentation 

<img width="807" alt="SunZia" src="https://github.com/user-attachments/assets/43164dbf-2354-4e22-9b6d-32fa4f956ceb" />

2024-12-27 18:15 UTC, lawrenceccheung commented
Hi @hgopalan,

Thanks for documenting the process.  One question I have about the MMC coupling with terrain is how we account for the fact that the turbulence will take time to spin-up, and how a time-varying MMC profile can be accounted for.  One way to handle it is to include a large, flat inflow region where the turbulence can develop.  Depending on the ABL stability state, it might require a shorter/longer region for the turbulence profile to adjust.  

Once the 1D MMC profile is time-varying, though, that introduces a time delay between when the velocity/temperature changes and when that turbulence enters the domain.  @mchurchf and @ewquon might have some ideas on what to do too.

Lawrence

2024-12-27 18:27 UTC, hgopalan commented
> Hi @hgopalan,
> 
> Thanks for documenting the process. One question I have about the MMC coupling with terrain is how we account for the fact that the turbulence will take time to spin-up, and how a time-varying MMC profile can be accounted for. One way to handle it is to include a large, flat inflow region where the turbulence can develop. Depending on the ABL stability state, it might require a shorter/longer region for the turbulence profile to adjust.
> 
> Once the 1D MMC profile is time-varying, though, that introduces a time delay between when the velocity/temperature changes and when that turbulence enters the domain. @mchurchf and @ewquon might have some ideas on what to do too.
> 
> Lawrence

The purpose of this workflow  is mainly related to providing a simple method for AEP calculation for the RANS model similar to the method used in commercial RANS tools. The usability of the method and adoption for LES needs some investigation. If a terrain is complex, it does not need a lot of time to spin-up as the heterogeneity generate the flow structures. The terrain is smoothed in the horizontal boundaries and when they encounter a change in elevation  it generated the structures for the cases I tested with mountains. 

There is no restriction on specifying a time-varying 1-D profile. We just need to move the profile reader to be time-dependent. Will require some code changes but is doable. 

There is some difference with the method proposed here. Our aim is to match the met-mast data while providing a reasonable boundary condition which will not cause divergence of the pressure poisson solver. We are not worried about flow spin-up and other issues and expect that the presence of complex terrain will generate the structure. 

We may have to tweak the workflow in future if there are discrepancies with LES. However, this method should be acceptable for RANS.

2025-01-07 17:06 UTC, ewquon commented
> Hi @hgopalan,
> 
> Thanks for documenting the process. One question I have about the MMC coupling with terrain is how we account for the fact that the turbulence will take time to spin-up, and how a time-varying MMC profile can be accounted for. One way to handle it is to include a large, flat inflow region where the turbulence can develop. Depending on the ABL stability state, it might require a shorter/longer region for the turbulence profile to adjust.
> 
> Once the 1D MMC profile is time-varying, though, that introduces a time delay between when the velocity/temperature changes and when that turbulence enters the domain. @mchurchf and @ewquon might have some ideas on what to do too.
> 
> Lawrence

What we could do for terrain is instead of a planar average, use a temporal average at a specified location (e.g., at the met mast). There is a question of whether you make the forcing constant with altitude or constant with height AGL; you can also blend from the latter to the former.

2025-01-15 17:12 UTC, hgopalan commented
LES structures are not generated when the terrain is smooth. Added thermal perturbations to generate the flow structures. Sample result are shown for a flat surface without precursor and LES (dx=dy=60m). This is still preliminary and need further analysis on the strength of the structure on numerical stability for complex terrains. 

Horizontal Plane 

<img width="1043" alt="Horizontal" src="https://github.com/user-attachments/assets/20a98edf-9994-4db5-8c98-a96c10b90011" />

Vertical Plane 

<img width="1135" alt="Vertical" src="https://github.com/user-attachments/assets/56464d76-4e9f-42af-8b41-2d2a60a290f5" />

2025-01-23 15:39 UTC, hgopalan commented
Added regression tests with and without perturbation forcing

2025-01-24 17:13 UTC, marchdf reviewed
Thanks for adding this in! I made a first pass. LMK when I can do a second one.

2025-01-24 17:13 UTC, marchdf commented on docs/sphinx/user/features.rst
> +   * Sponge layer driven ABL simulations
I am a bit confused. Why is this in the boundary condition section? This feels like just another element in the bullet `* Atmospheric boundary layer (ABL):`

2025-01-24 17:13 UTC, marchdf commented on amr-wind/equation_systems/temperature/source_terms/TemperatureFreeAtmosphereForcing.H
> +    amrex::Real m_sponge_distance_west{-1000};
are these just mean to be big numbers? If so, use the ones in `constants`

2025-01-24 17:13 UTC, marchdf commented on amr-wind/equation_systems/temperature/source_terms/PertForcing.H
> +    int m_time_index{100};
is 100 a good default value? I would think it should be either a big value or a small value?

2025-01-24 17:18 UTC, hgopalan commented on docs/sphinx/user/features.rst
> +   * Sponge layer driven ABL simulations
This is a different way of specifying the boundary conditions through a fringe or sponge layer to force the simulations.

2025-01-24 17:19 UTC, hgopalan commented on amr-wind/equation_systems/temperature/source_terms/TemperatureFreeAtmosphereForcing.H
> +    amrex::Real m_sponge_distance_west{-1000};
The distances are measured in meters within the domain. We use between 1-3 kms of sponge.

2025-01-24 17:20 UTC, hgopalan commented on amr-wind/equation_systems/temperature/source_terms/PertForcing.H
> +    int m_time_index{100};
This number represents how often we add the perturbations. If we add too often it will cause numerical instability. Also if it is a large number the structures dissipate.

2025-01-28 18:49 UTC, marchdf requested changes

2025-01-28 18:49 UTC, marchdf commented on amr-wind/equation_systems/icns/source_terms/VelocityFreeAtmosphereForcing.H
> +    std::string m_1d_rans;
rename: `m_1d_rans_filename` or something like that.

2025-01-28 18:49 UTC, marchdf commented on amr-wind/equation_systems/icns/source_terms/VelocityFreeAtmosphereForcing.cpp
> +    if (has_terrain) {
let's consolidate these 2 branches since they look so similar. I think the only difference is the calculation of z? I would move the `if has_terrain` into the parallel for. It's not ideal but I would rather than then the code duplication.

2025-01-28 18:49 UTC, marchdf commented on amr-wind/equation_systems/icns/source_terms/VelocityFreeAtmosphereForcing.cpp
> +    if (has_terrain) {
Or do it like you do below with the perturbation forcing

2025-01-28 18:49 UTC, marchdf commented on amr-wind/equation_systems/temperature/source_terms/PerturbationForcing.cpp
> +                if (pert_box.contains(point)) {
nicely done

2025-01-28 18:49 UTC, marchdf commented on amr-wind/equation_systems/temperature/source_terms/TemperatureFreeAtmosphereForcing.cpp
> +        amrex::ParallelFor(
this also looks like the one on L144. Think you can consolidate that?

2025-01-28 18:50 UTC, marchdf commented
Good work, just had some thoughts for avoiding some duplicate code. I am running the tests on GPU now.

2025-01-29 18:50 UTC, moprak-nrel reviewed
Good work! Have a few quick questions on the actual model.

2025-01-29 18:50 UTC, moprak-nrel commented on amr-wind/equation_systems/tke/source_terms/KransAxell.cpp
> +            1.0 / dt * (tke_arr(i, j, k) - ref_tke);
Is the `1/dt` fixing a previous bug? The dimensions of the `sponge_forcing` array should now be different right?

2025-01-29 19:45 UTC, hgopalan commented on amr-wind/equation_systems/temperature/source_terms/TemperatureFreeAtmosphereForcing.H
> +    amrex::Real m_meso_timescale{30};
the 30 seconds is sort of commonly used.

2025-01-29 19:46 UTC, hgopalan commented on amr-wind/equation_systems/tke/source_terms/KransAxell.cpp
> +            const amrex::Real ustar = m * kappa / std::log(3 * z / z0);
Because we use the forcing term to set the boundary condition, cannot use the value of the cell in which the forcing term is set and we use something above it.

2025-01-29 19:47 UTC, hgopalan commented on amr-wind/equation_systems/tke/source_terms/KransAxell.cpp
> +            1.0 / dt * (tke_arr(i, j, k) - ref_tke);
Changing to 1/dt helped in speeding the convergence and reducing oscillation in the free atmosphere

2025-01-29 20:13 UTC, moprak-nrel commented on amr-wind/equation_systems/tke/source_terms/KransAxell.cpp
> +            1.0 / dt * (tke_arr(i, j, k) - ref_tke);
Does the dimensional change not matter? It changed from `[No-units] * tke` to `[1/T] * tke`? or is the `1` some type of dimensional constant?

2025-01-29 22:37 UTC, hgopalan commented on amr-wind/equation_systems/tke/source_terms/KransAxell.cpp
> +            1.0 / dt * (tke_arr(i, j, k) - ref_tke);
The original zi also had a model constant which basically returns 1/s. It was never explicitly mentioned.

2025-01-30 17:49 UTC, hgopalan commented on amr-wind/equation_systems/tke/source_terms/KransAxell.H
> +    int m_sponge_west{0};
I kept them as ints for future modifications when the different boundaries can have other non-zero positive values when we use different driving winds

2025-01-30 17:49 UTC, hgopalan commented on amr-wind/equation_systems/tke/source_terms/KransAxell.cpp
> +            const int sponge_east = m_sponge_east;
Same as above. Currently it is 1/0 but there will be future changes when they can be positive integers

2025-01-30 18:02 UTC, moprak-nrel commented on amr-wind/equation_systems/tke/source_terms/KransAxell.cpp
> +            const int sponge_east = m_sponge_east;
one last question: would that int work with 

```
                    amrex::Real xi_start =
                        (start_west - x) / (start_west - problo[0]);
                    xi_start = sponge_west * std::max(xi_start, 0.0);
                    xstart_damping =
                        sponge_west * sponge_strength * xi_start * xi_start;
```

That int seems to be multiplied as a cubed power in the damping calculation

2025-01-30 18:12 UTC, marchdf approved these changes

2025-01-30 20:08 UTC, moprak-nrel approved these changes

2025-01-30 20:41 UTC, merged