Added NREL 5MW Openfast example
Exawind/amr-wind pull request #388
Opened 2021-04-09 21:37 UTC by tonyinme

Hey @jrood-nrel and @sayerhs, I am adding this pull request to start the process on getting an example that uses openfast within the repository. @sayerhs mentioned we might not be ready for this yet, but I'd like to have this here so we don't forget. Let me know what else I should do.

Thanks!
Tony

2022-01-21 22:36 UTC, psakievich requested changes
I marked a few of them, but there are multiple hard absolute coded paths in here that are not suitable for merging. There are also some binary files that should be removed.  I think what we need to do here is create a new repository specifically for managing this test that will compile the servo library and make that a submodule to amr-wind and nalu-wind

2022-01-21 22:36 UTC, psakievich commented on test/test_files/act_openfast_nrel5mw/fast_inp/5MW_Baseline/ServoData/Makefile
> +# CMAKE generated file: DO NOT EDIT!
this file needs to be deleted

2022-01-21 22:36 UTC, psakievich commented on test/test_files/act_openfast_nrel5mw/fast_inp/5MW_Baseline/ServoData/CTestTestfile.cmake
> +# CMake generated Testfile for
this file needs to remove hard coded paths to @tonyinme 's home directory

2022-01-21 22:36 UTC, psakievich commented on test/test_files/act_openfast_nrel5mw/fast_inp/5MW_Baseline/ServoData/CMakeFiles/progress.marks
> +0
probably delete this one too

2022-01-21 22:36 UTC, psakievich commented on test/test_files/act_openfast_nrel5mw/fast_inp/5MW_Baseline/ServoData/CMakeFiles/DISCON.dir/DependInfo.cmake
> +  "/home/lmartine/nalu-wind/reg_tests/test_files/nrel5MWactuatorLine/5MW_Baseline/ServoData/DISCON.F90" "/home/lmartine/nalu-wind/build/reg_tests/test_files/nrel5MWactuatorLine/5MW_Baseline/ServoData
these hard coded paths aren't mergable

2022-01-21 22:36 UTC, psakievich commented on test/test_files/act_openfast_nrel5mw/fast_inp/5MW_Baseline/ServoData/CMakeFiles/CMakeDirectoryInformation.cmake
> +set(CMAKE_RELATIVE_PATH_TOP_SOURCE "/home/lmartine/nalu-wind")
these hard coded paths aren't mergable

2022-01-24 17:45 UTC, tonyinme commented
Thanks @psakievich , I deleted the extra files.

2024-02-22 01:59 UTC, closed without merging